// Code generated by "enumer -type=OpType -output=gen_optype_enumer.go optypes.go"; DO NOT EDIT.

package optypes

import (
	"fmt"
	"strings"
)

const _OpTypeName = "InvalidFuncReturnConstantIdentityAbsAddAllReduceAndAtan2BatchNormInferenceBatchNormTrainingBatchNormGradBitcastConvertBroadcastInDimCbrtCeilClampCollectiveBroadcastCompareComplexConcatenateConvertConvolutionCosineCountLeadingZerosDivideDotGeneralDynamicSliceDynamicUpdateSliceErfExponentialExponentialMinusOneFftFloorGatherImagIsFiniteIotaLogLogPlusOneLogisticMaximumMinimumMultiplyNegateNotOrPadPopcntPowerRealRemainderReduceReduceWindowReshapeReverseRNGBitGeneratorRoundNearestAfzRoundNearestEvenRsqrtScatterSelectSelectAndScatterShiftLeftShiftRightArithmeticShiftRightLogicalSignSineSliceSortSqrtSubtractTanTanhTransposeXorAllGatherAllToAllCaseCholeskyCollectivePermuteCompositeCustomCallDynamicBroadcastInDimDynamicConvDynamicGatherDynamicIotaDynamicPadDynamicReshapeGetDimensionSizeGetTupleElementIfInfeedOptimizationBarrierOutfeedPartitionIdRecvReducePrecisionReduceScatterSendTriangularSolveTupleUniformDequantizeUniformQuantizeWhileLast"

var _OpTypeIndex = [...]uint16{0, 7, 17, 25, 33, 36, 39, 48, 51, 56, 74, 91, 104, 118, 132, 136, 140, 145, 164, 171, 178, 189, 196, 207, 213, 230, 236, 246, 258, 276, 279, 290, 309, 312, 317, 323, 327, 335, 339, 342, 352, 360, 367, 374, 382, 388, 391, 393, 396, 402, 407, 411, 420, 426, 438, 445, 452, 467, 482, 498, 503, 510, 516, 532, 541, 561, 578, 582, 586, 591, 595, 599, 607, 610, 614, 623, 626, 635, 643, 647, 655, 672, 681, 691, 712, 723, 736, 747, 757, 771, 787, 802, 804, 810, 829, 836, 847, 851, 866, 879, 883, 898, 903, 920, 935, 940, 944}

const _OpTypeLowerName = "invalidfuncreturnconstantidentityabsaddallreduceandatan2batchnorminferencebatchnormtrainingbatchnormgradbitcastconvertbroadcastindimcbrtceilclampcollectivebroadcastcomparecomplexconcatenateconvertconvolutioncosinecountleadingzerosdividedotgeneraldynamicslicedynamicupdatesliceerfexponentialexponentialminusonefftfloorgatherimagisfiniteiotaloglogplusonelogisticmaximumminimummultiplynegatenotorpadpopcntpowerrealremainderreducereducewindowreshapereverserngbitgeneratorroundnearestafzroundnearestevenrsqrtscatterselectselectandscattershiftleftshiftrightarithmeticshiftrightlogicalsignsineslicesortsqrtsubtracttantanhtransposexorallgatheralltoallcasecholeskycollectivepermutecompositecustomcalldynamicbroadcastindimdynamicconvdynamicgatherdynamiciotadynamicpaddynamicreshapegetdimensionsizegettupleelementifinfeedoptimizationbarrieroutfeedpartitionidrecvreduceprecisionreducescattersendtriangularsolvetupleuniformdequantizeuniformquantizewhilelast"

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpTypeIndex)-1) {
		return fmt.Sprintf("OpType(%d)", i)
	}
	return _OpTypeName[_OpTypeIndex[i]:_OpTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OpTypeNoOp() {
	var x [1]struct{}
	_ = x[Invalid-(0)]
	_ = x[FuncReturn-(1)]
	_ = x[Constant-(2)]
	_ = x[Identity-(3)]
	_ = x[Abs-(4)]
	_ = x[Add-(5)]
	_ = x[AllReduce-(6)]
	_ = x[And-(7)]
	_ = x[Atan2-(8)]
	_ = x[BatchNormInference-(9)]
	_ = x[BatchNormTraining-(10)]
	_ = x[BatchNormGrad-(11)]
	_ = x[BitcastConvert-(12)]
	_ = x[BroadcastInDim-(13)]
	_ = x[Cbrt-(14)]
	_ = x[Ceil-(15)]
	_ = x[Clamp-(16)]
	_ = x[CollectiveBroadcast-(17)]
	_ = x[Compare-(18)]
	_ = x[Complex-(19)]
	_ = x[Concatenate-(20)]
	_ = x[Convert-(21)]
	_ = x[Convolution-(22)]
	_ = x[Cosine-(23)]
	_ = x[CountLeadingZeros-(24)]
	_ = x[Divide-(25)]
	_ = x[DotGeneral-(26)]
	_ = x[DynamicSlice-(27)]
	_ = x[DynamicUpdateSlice-(28)]
	_ = x[Erf-(29)]
	_ = x[Exponential-(30)]
	_ = x[ExponentialMinusOne-(31)]
	_ = x[Fft-(32)]
	_ = x[Floor-(33)]
	_ = x[Gather-(34)]
	_ = x[Imag-(35)]
	_ = x[IsFinite-(36)]
	_ = x[Iota-(37)]
	_ = x[Log-(38)]
	_ = x[LogPlusOne-(39)]
	_ = x[Logistic-(40)]
	_ = x[Maximum-(41)]
	_ = x[Minimum-(42)]
	_ = x[Multiply-(43)]
	_ = x[Negate-(44)]
	_ = x[Not-(45)]
	_ = x[Or-(46)]
	_ = x[Pad-(47)]
	_ = x[Popcnt-(48)]
	_ = x[Power-(49)]
	_ = x[Real-(50)]
	_ = x[Remainder-(51)]
	_ = x[Reduce-(52)]
	_ = x[ReduceWindow-(53)]
	_ = x[Reshape-(54)]
	_ = x[Reverse-(55)]
	_ = x[RNGBitGenerator-(56)]
	_ = x[RoundNearestAfz-(57)]
	_ = x[RoundNearestEven-(58)]
	_ = x[Rsqrt-(59)]
	_ = x[Scatter-(60)]
	_ = x[Select-(61)]
	_ = x[SelectAndScatter-(62)]
	_ = x[ShiftLeft-(63)]
	_ = x[ShiftRightArithmetic-(64)]
	_ = x[ShiftRightLogical-(65)]
	_ = x[Sign-(66)]
	_ = x[Sine-(67)]
	_ = x[Slice-(68)]
	_ = x[Sort-(69)]
	_ = x[Sqrt-(70)]
	_ = x[Subtract-(71)]
	_ = x[Tan-(72)]
	_ = x[Tanh-(73)]
	_ = x[Transpose-(74)]
	_ = x[Xor-(75)]
	_ = x[AllGather-(76)]
	_ = x[AllToAll-(77)]
	_ = x[Case-(78)]
	_ = x[Cholesky-(79)]
	_ = x[CollectivePermute-(80)]
	_ = x[Composite-(81)]
	_ = x[CustomCall-(82)]
	_ = x[DynamicBroadcastInDim-(83)]
	_ = x[DynamicConv-(84)]
	_ = x[DynamicGather-(85)]
	_ = x[DynamicIota-(86)]
	_ = x[DynamicPad-(87)]
	_ = x[DynamicReshape-(88)]
	_ = x[GetDimensionSize-(89)]
	_ = x[GetTupleElement-(90)]
	_ = x[If-(91)]
	_ = x[Infeed-(92)]
	_ = x[OptimizationBarrier-(93)]
	_ = x[Outfeed-(94)]
	_ = x[PartitionId-(95)]
	_ = x[Recv-(96)]
	_ = x[ReducePrecision-(97)]
	_ = x[ReduceScatter-(98)]
	_ = x[Send-(99)]
	_ = x[TriangularSolve-(100)]
	_ = x[Tuple-(101)]
	_ = x[UniformDequantize-(102)]
	_ = x[UniformQuantize-(103)]
	_ = x[While-(104)]
	_ = x[Last-(105)]
}

var _OpTypeValues = []OpType{Invalid, FuncReturn, Constant, Identity, Abs, Add, AllReduce, And, Atan2, BatchNormInference, BatchNormTraining, BatchNormGrad, BitcastConvert, BroadcastInDim, Cbrt, Ceil, Clamp, CollectiveBroadcast, Compare, Complex, Concatenate, Convert, Convolution, Cosine, CountLeadingZeros, Divide, DotGeneral, DynamicSlice, DynamicUpdateSlice, Erf, Exponential, ExponentialMinusOne, Fft, Floor, Gather, Imag, IsFinite, Iota, Log, LogPlusOne, Logistic, Maximum, Minimum, Multiply, Negate, Not, Or, Pad, Popcnt, Power, Real, Remainder, Reduce, ReduceWindow, Reshape, Reverse, RNGBitGenerator, RoundNearestAfz, RoundNearestEven, Rsqrt, Scatter, Select, SelectAndScatter, ShiftLeft, ShiftRightArithmetic, ShiftRightLogical, Sign, Sine, Slice, Sort, Sqrt, Subtract, Tan, Tanh, Transpose, Xor, AllGather, AllToAll, Case, Cholesky, CollectivePermute, Composite, CustomCall, DynamicBroadcastInDim, DynamicConv, DynamicGather, DynamicIota, DynamicPad, DynamicReshape, GetDimensionSize, GetTupleElement, If, Infeed, OptimizationBarrier, Outfeed, PartitionId, Recv, ReducePrecision, ReduceScatter, Send, TriangularSolve, Tuple, UniformDequantize, UniformQuantize, While, Last}

var _OpTypeNameToValueMap = map[string]OpType{
	_OpTypeName[0:7]:          Invalid,
	_OpTypeLowerName[0:7]:     Invalid,
	_OpTypeName[7:17]:         FuncReturn,
	_OpTypeLowerName[7:17]:    FuncReturn,
	_OpTypeName[17:25]:        Constant,
	_OpTypeLowerName[17:25]:   Constant,
	_OpTypeName[25:33]:        Identity,
	_OpTypeLowerName[25:33]:   Identity,
	_OpTypeName[33:36]:        Abs,
	_OpTypeLowerName[33:36]:   Abs,
	_OpTypeName[36:39]:        Add,
	_OpTypeLowerName[36:39]:   Add,
	_OpTypeName[39:48]:        AllReduce,
	_OpTypeLowerName[39:48]:   AllReduce,
	_OpTypeName[48:51]:        And,
	_OpTypeLowerName[48:51]:   And,
	_OpTypeName[51:56]:        Atan2,
	_OpTypeLowerName[51:56]:   Atan2,
	_OpTypeName[56:74]:        BatchNormInference,
	_OpTypeLowerName[56:74]:   BatchNormInference,
	_OpTypeName[74:91]:        BatchNormTraining,
	_OpTypeLowerName[74:91]:   BatchNormTraining,
	_OpTypeName[91:104]:       BatchNormGrad,
	_OpTypeLowerName[91:104]:  BatchNormGrad,
	_OpTypeName[104:118]:      BitcastConvert,
	_OpTypeLowerName[104:118]: BitcastConvert,
	_OpTypeName[118:132]:      BroadcastInDim,
	_OpTypeLowerName[118:132]: BroadcastInDim,
	_OpTypeName[132:136]:      Cbrt,
	_OpTypeLowerName[132:136]: Cbrt,
	_OpTypeName[136:140]:      Ceil,
	_OpTypeLowerName[136:140]: Ceil,
	_OpTypeName[140:145]:      Clamp,
	_OpTypeLowerName[140:145]: Clamp,
	_OpTypeName[145:164]:      CollectiveBroadcast,
	_OpTypeLowerName[145:164]: CollectiveBroadcast,
	_OpTypeName[164:171]:      Compare,
	_OpTypeLowerName[164:171]: Compare,
	_OpTypeName[171:178]:      Complex,
	_OpTypeLowerName[171:178]: Complex,
	_OpTypeName[178:189]:      Concatenate,
	_OpTypeLowerName[178:189]: Concatenate,
	_OpTypeName[189:196]:      Convert,
	_OpTypeLowerName[189:196]: Convert,
	_OpTypeName[196:207]:      Convolution,
	_OpTypeLowerName[196:207]: Convolution,
	_OpTypeName[207:213]:      Cosine,
	_OpTypeLowerName[207:213]: Cosine,
	_OpTypeName[213:230]:      CountLeadingZeros,
	_OpTypeLowerName[213:230]: CountLeadingZeros,
	_OpTypeName[230:236]:      Divide,
	_OpTypeLowerName[230:236]: Divide,
	_OpTypeName[236:246]:      DotGeneral,
	_OpTypeLowerName[236:246]: DotGeneral,
	_OpTypeName[246:258]:      DynamicSlice,
	_OpTypeLowerName[246:258]: DynamicSlice,
	_OpTypeName[258:276]:      DynamicUpdateSlice,
	_OpTypeLowerName[258:276]: DynamicUpdateSlice,
	_OpTypeName[276:279]:      Erf,
	_OpTypeLowerName[276:279]: Erf,
	_OpTypeName[279:290]:      Exponential,
	_OpTypeLowerName[279:290]: Exponential,
	_OpTypeName[290:309]:      ExponentialMinusOne,
	_OpTypeLowerName[290:309]: ExponentialMinusOne,
	_OpTypeName[309:312]:      Fft,
	_OpTypeLowerName[309:312]: Fft,
	_OpTypeName[312:317]:      Floor,
	_OpTypeLowerName[312:317]: Floor,
	_OpTypeName[317:323]:      Gather,
	_OpTypeLowerName[317:323]: Gather,
	_OpTypeName[323:327]:      Imag,
	_OpTypeLowerName[323:327]: Imag,
	_OpTypeName[327:335]:      IsFinite,
	_OpTypeLowerName[327:335]: IsFinite,
	_OpTypeName[335:339]:      Iota,
	_OpTypeLowerName[335:339]: Iota,
	_OpTypeName[339:342]:      Log,
	_OpTypeLowerName[339:342]: Log,
	_OpTypeName[342:352]:      LogPlusOne,
	_OpTypeLowerName[342:352]: LogPlusOne,
	_OpTypeName[352:360]:      Logistic,
	_OpTypeLowerName[352:360]: Logistic,
	_OpTypeName[360:367]:      Maximum,
	_OpTypeLowerName[360:367]: Maximum,
	_OpTypeName[367:374]:      Minimum,
	_OpTypeLowerName[367:374]: Minimum,
	_OpTypeName[374:382]:      Multiply,
	_OpTypeLowerName[374:382]: Multiply,
	_OpTypeName[382:388]:      Negate,
	_OpTypeLowerName[382:388]: Negate,
	_OpTypeName[388:391]:      Not,
	_OpTypeLowerName[388:391]: Not,
	_OpTypeName[391:393]:      Or,
	_OpTypeLowerName[391:393]: Or,
	_OpTypeName[393:396]:      Pad,
	_OpTypeLowerName[393:396]: Pad,
	_OpTypeName[396:402]:      Popcnt,
	_OpTypeLowerName[396:402]: Popcnt,
	_OpTypeName[402:407]:      Power,
	_OpTypeLowerName[402:407]: Power,
	_OpTypeName[407:411]:      Real,
	_OpTypeLowerName[407:411]: Real,
	_OpTypeName[411:420]:      Remainder,
	_OpTypeLowerName[411:420]: Remainder,
	_OpTypeName[420:426]:      Reduce,
	_OpTypeLowerName[420:426]: Reduce,
	_OpTypeName[426:438]:      ReduceWindow,
	_OpTypeLowerName[426:438]: ReduceWindow,
	_OpTypeName[438:445]:      Reshape,
	_OpTypeLowerName[438:445]: Reshape,
	_OpTypeName[445:452]:      Reverse,
	_OpTypeLowerName[445:452]: Reverse,
	_OpTypeName[452:467]:      RNGBitGenerator,
	_OpTypeLowerName[452:467]: RNGBitGenerator,
	_OpTypeName[467:482]:      RoundNearestAfz,
	_OpTypeLowerName[467:482]: RoundNearestAfz,
	_OpTypeName[482:498]:      RoundNearestEven,
	_OpTypeLowerName[482:498]: RoundNearestEven,
	_OpTypeName[498:503]:      Rsqrt,
	_OpTypeLowerName[498:503]: Rsqrt,
	_OpTypeName[503:510]:      Scatter,
	_OpTypeLowerName[503:510]: Scatter,
	_OpTypeName[510:516]:      Select,
	_OpTypeLowerName[510:516]: Select,
	_OpTypeName[516:532]:      SelectAndScatter,
	_OpTypeLowerName[516:532]: SelectAndScatter,
	_OpTypeName[532:541]:      ShiftLeft,
	_OpTypeLowerName[532:541]: ShiftLeft,
	_OpTypeName[541:561]:      ShiftRightArithmetic,
	_OpTypeLowerName[541:561]: ShiftRightArithmetic,
	_OpTypeName[561:578]:      ShiftRightLogical,
	_OpTypeLowerName[561:578]: ShiftRightLogical,
	_OpTypeName[578:582]:      Sign,
	_OpTypeLowerName[578:582]: Sign,
	_OpTypeName[582:586]:      Sine,
	_OpTypeLowerName[582:586]: Sine,
	_OpTypeName[586:591]:      Slice,
	_OpTypeLowerName[586:591]: Slice,
	_OpTypeName[591:595]:      Sort,
	_OpTypeLowerName[591:595]: Sort,
	_OpTypeName[595:599]:      Sqrt,
	_OpTypeLowerName[595:599]: Sqrt,
	_OpTypeName[599:607]:      Subtract,
	_OpTypeLowerName[599:607]: Subtract,
	_OpTypeName[607:610]:      Tan,
	_OpTypeLowerName[607:610]: Tan,
	_OpTypeName[610:614]:      Tanh,
	_OpTypeLowerName[610:614]: Tanh,
	_OpTypeName[614:623]:      Transpose,
	_OpTypeLowerName[614:623]: Transpose,
	_OpTypeName[623:626]:      Xor,
	_OpTypeLowerName[623:626]: Xor,
	_OpTypeName[626:635]:      AllGather,
	_OpTypeLowerName[626:635]: AllGather,
	_OpTypeName[635:643]:      AllToAll,
	_OpTypeLowerName[635:643]: AllToAll,
	_OpTypeName[643:647]:      Case,
	_OpTypeLowerName[643:647]: Case,
	_OpTypeName[647:655]:      Cholesky,
	_OpTypeLowerName[647:655]: Cholesky,
	_OpTypeName[655:672]:      CollectivePermute,
	_OpTypeLowerName[655:672]: CollectivePermute,
	_OpTypeName[672:681]:      Composite,
	_OpTypeLowerName[672:681]: Composite,
	_OpTypeName[681:691]:      CustomCall,
	_OpTypeLowerName[681:691]: CustomCall,
	_OpTypeName[691:712]:      DynamicBroadcastInDim,
	_OpTypeLowerName[691:712]: DynamicBroadcastInDim,
	_OpTypeName[712:723]:      DynamicConv,
	_OpTypeLowerName[712:723]: DynamicConv,
	_OpTypeName[723:736]:      DynamicGather,
	_OpTypeLowerName[723:736]: DynamicGather,
	_OpTypeName[736:747]:      DynamicIota,
	_OpTypeLowerName[736:747]: DynamicIota,
	_OpTypeName[747:757]:      DynamicPad,
	_OpTypeLowerName[747:757]: DynamicPad,
	_OpTypeName[757:771]:      DynamicReshape,
	_OpTypeLowerName[757:771]: DynamicReshape,
	_OpTypeName[771:787]:      GetDimensionSize,
	_OpTypeLowerName[771:787]: GetDimensionSize,
	_OpTypeName[787:802]:      GetTupleElement,
	_OpTypeLowerName[787:802]: GetTupleElement,
	_OpTypeName[802:804]:      If,
	_OpTypeLowerName[802:804]: If,
	_OpTypeName[804:810]:      Infeed,
	_OpTypeLowerName[804:810]: Infeed,
	_OpTypeName[810:829]:      OptimizationBarrier,
	_OpTypeLowerName[810:829]: OptimizationBarrier,
	_OpTypeName[829:836]:      Outfeed,
	_OpTypeLowerName[829:836]: Outfeed,
	_OpTypeName[836:847]:      PartitionId,
	_OpTypeLowerName[836:847]: PartitionId,
	_OpTypeName[847:851]:      Recv,
	_OpTypeLowerName[847:851]: Recv,
	_OpTypeName[851:866]:      ReducePrecision,
	_OpTypeLowerName[851:866]: ReducePrecision,
	_OpTypeName[866:879]:      ReduceScatter,
	_OpTypeLowerName[866:879]: ReduceScatter,
	_OpTypeName[879:883]:      Send,
	_OpTypeLowerName[879:883]: Send,
	_OpTypeName[883:898]:      TriangularSolve,
	_OpTypeLowerName[883:898]: TriangularSolve,
	_OpTypeName[898:903]:      Tuple,
	_OpTypeLowerName[898:903]: Tuple,
	_OpTypeName[903:920]:      UniformDequantize,
	_OpTypeLowerName[903:920]: UniformDequantize,
	_OpTypeName[920:935]:      UniformQuantize,
	_OpTypeLowerName[920:935]: UniformQuantize,
	_OpTypeName[935:940]:      While,
	_OpTypeLowerName[935:940]: While,
	_OpTypeName[940:944]:      Last,
	_OpTypeLowerName[940:944]: Last,
}

var _OpTypeNames = []string{
	_OpTypeName[0:7],
	_OpTypeName[7:17],
	_OpTypeName[17:25],
	_OpTypeName[25:33],
	_OpTypeName[33:36],
	_OpTypeName[36:39],
	_OpTypeName[39:48],
	_OpTypeName[48:51],
	_OpTypeName[51:56],
	_OpTypeName[56:74],
	_OpTypeName[74:91],
	_OpTypeName[91:104],
	_OpTypeName[104:118],
	_OpTypeName[118:132],
	_OpTypeName[132:136],
	_OpTypeName[136:140],
	_OpTypeName[140:145],
	_OpTypeName[145:164],
	_OpTypeName[164:171],
	_OpTypeName[171:178],
	_OpTypeName[178:189],
	_OpTypeName[189:196],
	_OpTypeName[196:207],
	_OpTypeName[207:213],
	_OpTypeName[213:230],
	_OpTypeName[230:236],
	_OpTypeName[236:246],
	_OpTypeName[246:258],
	_OpTypeName[258:276],
	_OpTypeName[276:279],
	_OpTypeName[279:290],
	_OpTypeName[290:309],
	_OpTypeName[309:312],
	_OpTypeName[312:317],
	_OpTypeName[317:323],
	_OpTypeName[323:327],
	_OpTypeName[327:335],
	_OpTypeName[335:339],
	_OpTypeName[339:342],
	_OpTypeName[342:352],
	_OpTypeName[352:360],
	_OpTypeName[360:367],
	_OpTypeName[367:374],
	_OpTypeName[374:382],
	_OpTypeName[382:388],
	_OpTypeName[388:391],
	_OpTypeName[391:393],
	_OpTypeName[393:396],
	_OpTypeName[396:402],
	_OpTypeName[402:407],
	_OpTypeName[407:411],
	_OpTypeName[411:420],
	_OpTypeName[420:426],
	_OpTypeName[426:438],
	_OpTypeName[438:445],
	_OpTypeName[445:452],
	_OpTypeName[452:467],
	_OpTypeName[467:482],
	_OpTypeName[482:498],
	_OpTypeName[498:503],
	_OpTypeName[503:510],
	_OpTypeName[510:516],
	_OpTypeName[516:532],
	_OpTypeName[532:541],
	_OpTypeName[541:561],
	_OpTypeName[561:578],
	_OpTypeName[578:582],
	_OpTypeName[582:586],
	_OpTypeName[586:591],
	_OpTypeName[591:595],
	_OpTypeName[595:599],
	_OpTypeName[599:607],
	_OpTypeName[607:610],
	_OpTypeName[610:614],
	_OpTypeName[614:623],
	_OpTypeName[623:626],
	_OpTypeName[626:635],
	_OpTypeName[635:643],
	_OpTypeName[643:647],
	_OpTypeName[647:655],
	_OpTypeName[655:672],
	_OpTypeName[672:681],
	_OpTypeName[681:691],
	_OpTypeName[691:712],
	_OpTypeName[712:723],
	_OpTypeName[723:736],
	_OpTypeName[736:747],
	_OpTypeName[747:757],
	_OpTypeName[757:771],
	_OpTypeName[771:787],
	_OpTypeName[787:802],
	_OpTypeName[802:804],
	_OpTypeName[804:810],
	_OpTypeName[810:829],
	_OpTypeName[829:836],
	_OpTypeName[836:847],
	_OpTypeName[847:851],
	_OpTypeName[851:866],
	_OpTypeName[866:879],
	_OpTypeName[879:883],
	_OpTypeName[883:898],
	_OpTypeName[898:903],
	_OpTypeName[903:920],
	_OpTypeName[920:935],
	_OpTypeName[935:940],
	_OpTypeName[940:944],
}

// OpTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OpTypeString(s string) (OpType, error) {
	if val, ok := _OpTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OpTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OpType values", s)
}

// OpTypeValues returns all values of the enum
func OpTypeValues() []OpType {
	return _OpTypeValues
}

// OpTypeStrings returns a slice of all String values of the enum
func OpTypeStrings() []string {
	strs := make([]string, len(_OpTypeNames))
	copy(strs, _OpTypeNames)
	return strs
}

// IsAOpType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OpType) IsAOpType() bool {
	for _, v := range _OpTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
